"""The regions a traveller may say they live in — the unit a post's jurisdiction is drawn in.

TODO item 71, DECISIONS entry 252. Where a traveller applies often turns on where in a country they
live, and missions publish that split by state, province or nation: South Korea sends Maharashtra
to Mumbai and Tamil Nadu to Chennai; Germany sends Scotland to Edinburgh. So the traveller picks a
region, never types a city: the plan then matches the region against the page's own list, with no
geography to infer.

The list is committed data, `regions.yaml`, generated offline from GeoNames' first-level
administrative divisions by `visa-discover regions`. A region not in it is refused, never guessed.
"""

import csv
from collections.abc import Iterable
from functools import lru_cache
from typing import Any

import yaml

from visa_research_agent.config.loader import config_path

REGIONS_FILENAME = "regions.yaml"

_HEADER = """\
# The regions a traveller may choose after their country (TODO item 71, DECISIONS entry 252).
#
# GENERATED by `visa-discover regions --geonames admin1CodesASCII.txt` — do not edit by hand;
# regenerate instead. One list per country in countries.yaml: GeoNames' first-level
# administrative divisions, by their English names. A country absent here has no region field.
#
# Source: GeoNames, https://download.geonames.org/export/dump/admin1CodesASCII.txt
# Licence: Creative Commons Attribution 4.0 (https://creativecommons.org/licenses/by/4.0/),
# GeoNames (https://www.geonames.org/).
"""


@lru_cache(maxsize=1)
def get_regions() -> dict[str, tuple[str, ...]]:
    """Every country's regions, keyed by ISO alpha-2 code."""

    with config_path(REGIONS_FILENAME).open(encoding="utf-8") as handle:
        raw: Any = yaml.safe_load(handle) or {}
    return {code: tuple(names) for code, names in raw.items()}


def regions_for(country: str) -> tuple[str, ...]:
    """A country's regions, or none when the reference data has none for it."""

    return get_regions().get(country, ())


def normalise_region(country: str, value: str) -> str:
    """The region as the reference data spells it, or a refusal when it is not one of them.

    Case and spacing are forgiven; anything else is not. A city, a misspelling or another
    country's region is refused rather than matched, because a guessed region names a post.
    """

    wanted = " ".join(value.split()).casefold()
    for region in regions_for(country):
        if region.casefold() == wanted:
            return region
    raise ValueError(f"{value.strip()} is not a region this agent holds for {country}")


def regions_from_geonames(lines: Iterable[str], countries: Iterable[str]) -> dict[str, list[str]]:
    """Each wanted country's first-level divisions, from GeoNames' `admin1CodesASCII.txt`.

    A row is `CC.code<TAB>name<TAB>ascii name<TAB>geonameid`. The UTF-8 name is kept, because it is
    the one a traveller recognises ("Île-de-France"); names are de-duplicated and sorted.
    """

    wanted = set(countries)
    regions: dict[str, set[str]] = {}
    for row in csv.reader(lines, delimiter="\t", quoting=csv.QUOTE_NONE):
        if len(row) < 2 or "." not in row[0]:
            continue
        country = row[0].split(".", 1)[0]
        name = row[1].strip()
        if country in wanted and name:
            regions.setdefault(country, set()).add(name)
    return {code: sorted(names, key=str.casefold) for code, names in sorted(regions.items())}


def render_regions_yaml(regions: dict[str, list[str]]) -> str:
    """The committed file: its header, then one block per country."""

    body = yaml.safe_dump(regions, allow_unicode=True, sort_keys=True, width=100)
    return _HEADER + "\n" + body
