"""Building each government's checked link per destination, offline (DECISIONS entry 260).

The panel shows a link and nothing else, so the only thing worth building is a link that is right:
this government's page for this destination. Each reviewed row in `advisory_publishers.yaml` says
how to find one — an address pattern, an index read once and matched by the destination's name in
the government's own language, or the government's own published data — and every link found is
**opened before it is written**, as the app fetches: our own user agent, `robots.txt` obeyed, TLS
verified, and a challenge or refusal never worked around. A link that does not open is left out,
and the panel falls back to the government's advice page.

A government that refuses us cannot have its links checked. Its destination links are written only
when its own published data names them (the State Department's JSON); otherwise it gets its advice
page alone.

Destination names come from `country_names.yaml`, generated from Wikidata by `country-names`.
"""

import asyncio
import re
import unicodedata
from collections.abc import Callable, Iterable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import quote, urljoin, urlsplit

import httpx
import yaml
from bs4 import BeautifulSoup

from visa_research_agent.discovery.advisories import (
    AdvisoryLinks,
    AdvisoryPublisher,
    AdvisoryPublishers,
)
from visa_research_agent.discovery.lexicon import Country
from visa_research_agent.domain.models import (
    BLOCKING_STATUS_CODES,
    REFUSAL_BODY_MARKERS,
    is_challenge,
)
from visa_research_agent.domain.trust import host_is_within, host_of
from visa_research_agent.research.robots import RobotsCache, RobotsVerdict

NAMES_FILENAME = "country_names.yaml"
US_FEED = "https://cadataapi.state.gov/api/TravelAdvisories"
DE_FEED = "https://www.auswaertiges-amt.de/opendata/travelwarning"
DE_PAGE = "https://www.auswaertiges-amt.de/de/-/{id}"

# The languages asked of Wikidata: every language a publisher row may name, with Norwegian Bokmål
# under its Wikidata code.
WIKIDATA_LANGUAGES = (
    "ar", "bg", "cs", "da", "de", "en", "es", "fi", "fr", "hr", "hu", "id", "it", "ja", "ko",
    "nb", "nl", "pl", "pt", "ro", "ru", "sk", "sl", "sr", "sv", "th", "zh",
)  # fmt: skip

SOFT_404 = re.compile(
    r"\b404\b|not found|page introuvable|nicht gefunden|no encontrad|niet gevonden"
)


def wikidata_query() -> str:
    """The SPARQL that lists each country's name in every publisher language."""

    languages = ", ".join(f'"{code}"' for code in WIKIDATA_LANGUAGES)
    return (
        "SELECT ?iso ?label WHERE { ?c wdt:P297 ?iso . ?c rdfs:label ?label . "
        f"FILTER(LANG(?label) IN ({languages})) }}"
    )


def names_from_wikidata(
    payload: dict[str, Any], codes: Iterable[str]
) -> dict[str, dict[str, list[str]]]:
    """Each country's names by language, from a Wikidata SPARQL JSON result.

    Several Wikidata items can carry one ISO code (a state and its historical predecessor), so every
    label is kept; matching only ever asks whether a link names one of them.
    """

    wanted = set(codes)
    names: dict[str, dict[str, list[str]]] = {}
    for binding in payload["results"]["bindings"]:
        code = binding["iso"]["value"]
        if code not in wanted:
            continue
        language = binding["label"]["xml:lang"]
        value = binding["label"]["value"]
        bucket = names.setdefault(code, {}).setdefault(language, [])
        if value not in bucket:
            bucket.append(value)
    return {code: dict(sorted(by_language.items())) for code, by_language in sorted(names.items())}


NAMES_HEADER = """\
# Each country's name in the languages travel-advice publishers write in (DECISIONS entry 260).
#
# GENERATED by `visa-discover country-names` from Wikidata (rdfs:label of each item with ISO
# 3166-1 code P297) — do not edit by hand. Read offline only, to match a government's index of
# destination pages; nothing here reaches a traveller.
#
# Source: Wikidata, https://www.wikidata.org/ — CC0.
"""


def write_names(names: dict[str, dict[str, list[str]]], path: Path) -> None:
    body = yaml.safe_dump(names, sort_keys=False, allow_unicode=True, width=100)
    path.write_text(NAMES_HEADER + body, encoding="utf-8")


def load_names(path: Path) -> dict[str, dict[str, list[str]]]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def normalise(text: str) -> str:
    """Lower case, accents dropped, anything not a letter or digit a single space."""

    decomposed = unicodedata.normalize("NFKD", text.casefold())
    stripped = "".join(ch for ch in decomposed if not unicodedata.combining(ch))
    return " ".join(re.split(r"[\W_]+", stripped)).strip()


def slugify(text: str) -> str:
    return normalise(text).replace(" ", "-")


@dataclass
class Destination:
    country: Country
    names: dict[str, list[str]]

    def in_language(self, language: str) -> list[str]:
        own = self.names.get(language, [])
        english = [self.country.name, *self.country.synonyms, *self.names.get("en", [])]
        return list(dict.fromkeys([*own, *english]))


@dataclass
class CheckResult:
    url: str
    ok: bool
    reason: str = ""


@dataclass
class PublisherBuild:
    code: str
    links: dict[str, str] = field(default_factory=dict)
    missing: list[str] = field(default_factory=list)
    problems: list[str] = field(default_factory=list)


class LinkChecker:
    """Opens a link as the app would, and says whether it is a real page on the row's domains."""

    def __init__(
        self,
        client: httpx.AsyncClient,
        robots: RobotsCache,
        *,
        sleep: Callable[[float], Any] = asyncio.sleep,
        pause_seconds: float = 1.0,
    ) -> None:
        self.client = client
        self.robots = robots
        self.sleep = sleep
        self.pause_seconds = pause_seconds
        self._locks: dict[str, asyncio.Lock] = {}

    async def get(self, url: str) -> httpx.Response | str:
        """The response, or why it was not fetched."""

        verdict = await self.robots.verdict(self.client, url)
        if verdict is not RobotsVerdict.ALLOWED:
            return f"robots.txt {verdict.value}"
        lock = self._locks.setdefault(host_of(url), asyncio.Lock())
        async with lock:
            try:
                response = await self.client.get(url)
            except httpx.HTTPError as exc:
                return f"transport error ({type(exc).__name__})"
            await self.sleep(self.pause_seconds)
        return response

    async def check(self, url: str, domains: list[str]) -> CheckResult:
        got = await self.get(url)
        if isinstance(got, str):
            return CheckResult(url, False, got)
        final = str(got.url)
        if not host_is_within(host_of(final), domains):
            return CheckResult(url, False, f"redirected off the government's domains to {final}")
        body = got.text[:200_000] if "html" in got.headers.get("content-type", "") else ""
        lowered = body[:20_000].lower()
        if any(marker in lowered for marker in REFUSAL_BODY_MARKERS):
            return CheckResult(url, False, "refused")
        if is_challenge(got.status_code, got.headers, body[:20_000]):
            return CheckResult(url, False, "challenged")
        if got.status_code in BLOCKING_STATUS_CODES or got.status_code >= 400:
            return CheckResult(url, False, f"HTTP {got.status_code}")
        asked = urlsplit(url).path.rstrip("/").lower()
        landed = urlsplit(final).path.rstrip("/").lower()
        if landed != asked and asked.startswith(landed):
            # Sent back up to an index or the home page: the destination page does not exist.
            return CheckResult(url, False, f"redirected to {final}")
        title = BeautifulSoup(body, "html.parser").title if body else None
        if title and SOFT_404.search(title.get_text(" ", strip=True).lower()):
            return CheckResult(url, False, "a not-found page")
        # Kept as asked: it is the address that opened, and a redirect target can carry session or
        # preview parameters (Germany's `?isLocal=false&isPreview=false`).
        return CheckResult(url, True)


def _feed_stem(title: str) -> str:
    """A feed title's country, as the destination names spell it: "Kingdom of Denmark" is
    Denmark and "Mexico Travel Advisory" is Mexico."""

    stem = normalise(title).removesuffix(" travel advisory")
    for prefix in ("kingdom of ", "republic of ", "the ", "mainland "):
        stem = stem.removeprefix(prefix)
    return stem


def _why(got: httpx.Response | str) -> str:
    return got if isinstance(got, str) else f"HTTP {got.status_code}"


def pattern_candidates(pattern: str, destination: Destination, language: str) -> list[str]:
    country = destination.country
    values: dict[str, list[str]] = {
        "{ISO2}": [country.code],
        "{iso2}": [country.code.lower()],
        "{ISO3}": [country.alpha3],
        "{slug}": list(dict.fromkeys(slugify(n) for n in destination.in_language("en"))),
        "{name}": [quote(n) for n in destination.names.get(language, [])],
        "{name-slug}": list(dict.fromkeys(slugify(n) for n in destination.in_language(language))),
    }
    for placeholder, options in values.items():
        if placeholder in pattern:
            return [pattern.replace(placeholder, option) for option in options]
    return [pattern]


def index_matches(
    html: str, base_url: str, row: AdvisoryPublisher, destination: Destination
) -> list[str]:
    """Links on a government's index whose text or last path segment names the destination."""

    assert row.destinations is not None and row.destinations.link_prefix
    wanted = {normalise(name) for name in destination.in_language(row.language)}
    wanted.discard("")
    found: list[str] = []
    for anchor in BeautifulSoup(html, "html.parser").find_all("a", href=True):
        href = urljoin(base_url, str(anchor["href"])).split("#")[0]
        parts = urlsplit(href)
        if not parts.path.startswith(row.destinations.link_prefix):
            continue
        if not host_is_within(parts.hostname or "", row.domains):
            continue
        segments = [s for s in parts.path.split("/") if s]
        last = normalise(segments[-1].rsplit(".", 1)[0]) if segments else ""
        text = normalise(anchor.get_text(" ", strip=True))
        prefix_tail = normalise(parts.path[len(row.destinations.link_prefix) :].split("/")[0])
        if text in wanted or last in wanted or prefix_tail in wanted:
            found.append(href)
    return list(dict.fromkeys(found))


async def build_publisher(
    row: AdvisoryPublisher,
    destinations: list[Destination],
    checker: LinkChecker,
) -> PublisherBuild:
    build = PublisherBuild(row.code)
    method = row.destinations.method if row.destinations else None
    targets = [d for d in destinations if d.country.code != row.code]

    if method == "us_feed":
        # The State Department refuses our client, so its pages cannot be opened — but its own
        # published data names each one, which is the only way a refusing government's page for a
        # destination may be linked.
        got = await checker.get(US_FEED)
        if isinstance(got, str) or got.status_code != 200:
            build.problems.append(f"the feed could not be read: {_why(got)}")
            return build
        by_name: dict[str, str] = {}
        for item in got.json():
            if " - " not in item.get("Title", ""):
                continue
            country_part = item["Title"].split(" - ")[0]
            # "Mainland China, Hong Kong & Macau" is one advisory for three places.
            for part in [country_part, *re.split(r",|&", country_part)]:
                by_name.setdefault(_feed_stem(part), item["Link"])
        for destination in targets:
            keys = [normalise(n) for n in destination.in_language("en")]
            link = next((by_name[key] for key in keys if key in by_name), None)
            if link and host_is_within(host_of(link), row.domains):
                build.links[destination.country.code] = link
            else:
                build.missing.append(destination.country.code)
        return build

    if method == "de_feed":
        got = await checker.get(DE_FEED)
        if isinstance(got, str) or got.status_code != 200:
            build.problems.append("the feed could not be read")
            return build
        ids = {
            entry.get("countryCode"): content_id
            for content_id, entry in got.json()["response"].items()
            if isinstance(entry, dict)
        }
        for destination in targets:
            content_id = ids.get(destination.country.code)
            if content_id is None:
                build.missing.append(destination.country.code)
                continue
            result = await checker.check(DE_PAGE.format(id=content_id), row.domains)
            if result.ok:
                build.links[destination.country.code] = result.url
            else:
                build.missing.append(f"{destination.country.code} ({result.reason})")
        return build

    if row.access != "open" or row.destinations is None:
        return build

    index_html = ""
    if method == "index":
        assert row.destinations.index
        got = await checker.get(row.destinations.index)
        if isinstance(got, str) or got.status_code != 200:
            build.problems.append(f"the index could not be read: {_why(got)}")
            return build
        index_html = got.text
        index_url = str(got.url)
        if row.destinations.depth == 2:
            # An index of regions, each listing its countries: read each region page once too.
            prefix = row.destinations.link_prefix or ""
            regions = []
            for anchor in BeautifulSoup(index_html, "html.parser").find_all("a", href=True):
                href = urljoin(index_url, str(anchor["href"])).split("#")[0]
                tail = urlsplit(href).path[len(prefix) :].strip("/")
                if urlsplit(href).path.startswith(prefix) and tail and "/" not in tail:
                    regions.append(href)
            for region in list(dict.fromkeys(regions))[:12]:
                page = await checker.get(region)
                if not isinstance(page, str) and page.status_code == 200:
                    index_html += page.text

    for destination in targets:
        if method == "pattern":
            assert row.destinations.pattern
            candidates = pattern_candidates(row.destinations.pattern, destination, row.language)
        else:
            candidates = index_matches(index_html, index_url, row, destination)
        reasons = []
        for candidate in candidates[:4]:
            result = await checker.check(candidate, row.domains)
            if result.ok:
                build.links[destination.country.code] = result.url
                break
            reasons.append(result.reason)
        else:
            note = f" ({reasons[0]})" if reasons else ""
            if not reasons and method == "index":
                note = " (not on the index)"
            build.missing.append(destination.country.code + note)
    return build


async def build_advisory_links(
    publishers: AdvisoryPublishers,
    destinations: list[Destination],
    checker: LinkChecker,
    *,
    existing: AdvisoryLinks | None = None,
    only: set[str] | None = None,
    now: Callable[[], datetime] = lambda: datetime.now(UTC),
    on_progress: Callable[[PublisherBuild], None] | None = None,
) -> tuple[AdvisoryLinks, list[PublisherBuild]]:
    """Every government's checked destination links; rows outside `only` keep what they had."""

    links = dict(existing.links) if existing else {}
    semaphore = asyncio.Semaphore(6)

    async def one(row: AdvisoryPublisher) -> PublisherBuild:
        async with semaphore:
            build = await build_publisher(row, destinations, checker)
        if on_progress is not None:
            on_progress(build)
        return build

    rows = [row for row in publishers.publishers if not only or row.code in only]
    builds = await asyncio.gather(*(one(row) for row in rows))
    for build in builds:
        if build.links:
            links[build.code] = dict(sorted(build.links.items()))
        else:
            links.pop(build.code, None)
    built = AdvisoryLinks(schema_version=1, generated_at=now(), links=dict(sorted(links.items())))
    return built, list(builds)


LINKS_HEADER = """\
# Each government's page for each destination, checked (DECISIONS entry 260).
#
# GENERATED by `visa-discover advisory-links` from advisory_publishers.yaml — do not edit by hand.
# A link is written only after it opened for us under our own user agent, robots.txt obeyed; for a
# government that refuses us, only when its own published data names it. A destination missing
# here gets the government's advice page instead.
"""


def write_links(links: AdvisoryLinks, path: Path) -> None:
    payload = links.model_dump(mode="json")
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=200)
    path.write_text(LINKS_HEADER + body, encoding="utf-8")
