"""The places in a destination the weather panel offers: its capital and its largest cities.

The form names a country, and a country's weather is no one place's — Washington says little about
Florida. So the panel offers a short list, the capital first, and the traveller picks; nothing is
added to the visa form (DECISIONS entry 261).

The list is committed data, `destination_cities.yaml`, generated offline from GeoNames by
`visa-discover cities`, as `regions.yaml` is.
"""

import csv
import math
from collections.abc import Iterable
from functools import lru_cache
from typing import Any

import yaml

from visa_research_agent.config.loader import config_path
from visa_research_agent.domain.models import StrictModel

CITIES_FILENAME = "destination_cities.yaml"
CITIES_PER_COUNTRY = 8
DISTINCT_CITY_KM = 25.0

# GeoNames feature codes for a populated place a traveller would name. A section of a city (`PPLX`)
# or an abandoned or historical place is not one: Tokyo's wards would otherwise crowd out Osaka.
KEPT_FEATURES = {"PPL", "PPLA", "PPLA2", "PPLA3", "PPLA4", "PPLC", "PPLG", "PPLS"}

_HEADER = """\
# Each country's capital and largest cities, for the weather panel (DECISIONS entry 261).
#
# GENERATED by `visa-discover cities --geonames cities15000.txt` — do not edit by hand; regenerate
# instead. Per country: the capital first, then the most populous places, at most eight.
#
# Source: GeoNames, https://download.geonames.org/export/dump/cities15000.zip
# Licence: Creative Commons Attribution 4.0 (https://creativecommons.org/licenses/by/4.0/),
# GeoNames (https://www.geonames.org/).
"""


class City(StrictModel):
    name: str
    latitude: float
    longitude: float
    timezone: str
    capital: bool = False
    population: int = 0


def _km(a: "City", b: "City") -> float:
    rlat1, rlat2 = math.radians(a.latitude), math.radians(b.latitude)
    dlat, dlon = rlat2 - rlat1, math.radians(b.longitude - a.longitude)
    h = math.sin(dlat / 2) ** 2 + math.cos(rlat1) * math.cos(rlat2) * math.sin(dlon / 2) ** 2
    return 6371.0 * 2 * math.asin(math.sqrt(h))


def cities_from_geonames(rows: Iterable[list[str]], codes: Iterable[str]) -> dict[str, list[City]]:
    """Each country's capital and largest places, from GeoNames' tab-separated `cities` dump."""

    wanted = set(codes)
    by_country: dict[str, list[City]] = {}
    for row in rows:
        if len(row) < 18 or row[8] not in wanted or row[7] not in KEPT_FEATURES:
            continue
        by_country.setdefault(row[8], []).append(
            City(
                name=row[1],
                latitude=float(row[4]),
                longitude=float(row[5]),
                timezone=row[17],
                capital=row[7] == "PPLC",
                population=int(row[14] or 0),
            )
        )
    chosen: dict[str, list[City]] = {}
    for code, cities in sorted(by_country.items()):
        ordered = sorted(cities, key=lambda city: (not city.capital, -city.population, city.name))
        kept: list[City] = []
        for city in ordered:
            # A borough or district of a city already listed (Brooklyn, Delhi beside New Delhi,
            # Singapore's new towns) is that city's weather again, so it is not offered.
            if all(
                city.name != other.name and _km(city, other) > DISTINCT_CITY_KM for other in kept
            ):
                kept.append(city)
            if len(kept) == CITIES_PER_COUNTRY:
                break
        chosen[code] = kept
    return chosen


def read_geonames(path: str) -> list[list[str]]:
    with open(path, encoding="utf-8", newline="") as handle:
        return list(csv.reader(handle, delimiter="\t", quoting=csv.QUOTE_NONE))


def render_cities_yaml(cities: dict[str, list[City]]) -> str:
    payload = {
        code: [city.model_dump() for city in places] for code, places in sorted(cities.items())
    }
    return _HEADER + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=100)


@lru_cache(maxsize=1)
def get_cities() -> dict[str, tuple[City, ...]]:
    with config_path(CITIES_FILENAME).open(encoding="utf-8") as handle:
        raw: Any = yaml.safe_load(handle) or {}
    return {
        code: tuple(City.model_validate(city) for city in places) for code, places in raw.items()
    }


def cities_for(country: str) -> tuple[City, ...]:
    return get_cities().get(country, ())


def city_in(country: str, name: str | None) -> City | None:
    """The named city, or with no name the country's first — its capital where GeoNames marks one.

    A name not on the list is None, never the capital: showing Tokyo's weather to someone who asked
    for Sapporo would be a wrong answer presented as theirs.
    """

    places = cities_for(country)
    if name:
        wanted = name.casefold()
        return next((city for city in places if city.name.casefold() == wanted), None)
    return places[0] if places else None
